from pybreaker import CircuitBreaker
CIRCUIT_BREAKER_FAILURE_THRESHOLD = 20
CIRCUIT_BREAKER_RESET_TIMEOUT = 60 * 10
LOCATION_FETCH_BREAKER = CircuitBreaker(
    fail_max=CIRCUIT_BREAKER_FAILURE_THRESHOLD,
    reset_timeout=CIRCUIT_BREAKER_RESET_TIMEOUT
)
